id: A4A97E641
title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of Do Khyentsé
  Yeshé Dorjé
type: translation
pechas:
- IE35CC764
- ICE9AC649
- I3D309202
- I2C6B7AAD
- I608DCC3C
- IE096BEFE
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:29:07.670449
  last_modified_at: 2023-01-04 11:29:07.670457
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  IE35CC764/7691: 91EC
  ICE9AC649/A0B4: 91EC
  I3D309202/0F77: 91EC
  I2C6B7AAD/0A55: 91EC
  I608DCC3C/FD53: 91EC
  IE096BEFE/0EB3: 91EC
